import { AIReadingResponse } from '@/lib/deepseek'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Sparkles, RefreshCw, AlertCircle, ExternalLink } from 'lucide-react'
import { motion } from 'framer-motion'

interface AIReadingDisplayProps {
  aiReading: AIReadingResponse | null
  isLoading: boolean
  error: string | null
  errorDetails?: {
    type?: string
    helpUrl?: string
    action?: string
    waitTime?: number
    fields?: string[]
  } | null
  onRetry: () => void
  retryCount?: number
  cards?: Array<{
    id: number
    name: string
    position: number
  }>
  allCards?: any[]
  spreadId?: string
  question?: string
}

export function AIReadingDisplay({
  aiReading,
  isLoading,
  error,
  errorDetails,
  onRetry,
  retryCount = 0,
  cards,
  allCards,
  spreadId,
  question
}: AIReadingDisplayProps) {
  if (isLoading) {
    return (
      <Card className="border-border bg-card/50 backdrop-blur-sm">
        <CardContent className="p-8 text-center space-y-4">
          <div className="relative w-16 h-16 mx-auto">
            <div className="absolute inset-0 border-4 border-primary/20 rounded-full"></div>
            <div className="absolute inset-0 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
            <Sparkles className="absolute inset-0 m-auto w-6 h-6 text-primary animate-pulse" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-foreground">Generating your reading...</h3>
            <p className="text-muted-foreground text-sm mt-1">
              Just a moment...
            </p>
          </div>
        </CardContent>
      </Card>
    )
  }

  if (error) {
    return (
      <Alert variant="destructive" className="border-destructive/20 bg-destructive/5">
        <AlertCircle className="h-4 w-4" />
        <AlertTitle>Interpretation Unavailable</AlertTitle>
        <AlertDescription className="space-y-3">
          <p>{error}</p>
          {errorDetails && (
            <div className="text-sm opacity-90">
              {errorDetails.action && <p className="font-medium">{errorDetails.action}</p>}
              {errorDetails.helpUrl && (
                <a 
                  href={errorDetails.helpUrl} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 underline hover:text-destructive-foreground mt-1"
                >
                  View Help <ExternalLink className="w-3 h-3" />
                </a>
              )}
            </div>
          )}
          <Button 
            variant="outline" 
            size="sm" 
            onClick={onRetry}
            className="border-destructive/30 hover:bg-destructive/10 text-destructive-foreground mt-2"
          >
            <RefreshCw className="w-3 h-3 mr-2" />
            Try Again
          </Button>
        </AlertDescription>
      </Alert>
    )
  }

  if (!aiReading) {
    return null
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <Card className="border-primary/20 bg-card/50 backdrop-blur-sm overflow-hidden">
        <CardHeader className="bg-primary/5 border-b border-primary/10 pb-4">
          <CardTitle className="flex items-center gap-2 text-xl text-primary">
            <Sparkles className="w-5 h-5" />
            AI Interpretation
          </CardTitle>
        </CardHeader>
        <CardContent className="p-6 space-y-4">
          <div className="prose prose-invert max-w-none">
            <div className="whitespace-pre-wrap text-foreground/90 leading-relaxed">
              {aiReading.reading}
            </div>
          </div>
          
          <div className="pt-4 border-t border-border mt-4 flex justify-between items-center text-xs text-muted-foreground">
            <span>Generated by DeepSeek AI</span>
            {spreadId && <span>Spread: {spreadId}</span>}
          </div>
        </CardContent>
      </Card>
    </motion.div>
  )
}
